services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /secrets/postgres/POSTGRES_PASSWORD:/POSTGRES_PASSWORD:ro
    restart: unless-stopped
    shm_size: 1g
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          memory: 8g
networks:
  default:
    name: backend
volumes:
  postgres_data: null
